# Generated by Django 4.1 on 2024-04-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_alter_userip_failed'),
        ('patient', '0004_alter_patient_options_patient_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_patient', to='auth_service.userlogins'),
            preserve_default=False,
        ),
    ]
