# Generated by Django 4.0 on 2024-04-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='user_logins',
        ),
    ]
