# Generated by Django 4.0 on 2024-04-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth', models.JSONField(default=list)),
                ('time_stamp', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_chart', to='patient.patient')),
            ],
            options={
                'verbose_name': 'DentalChart',
                'verbose_name_plural': 'DentalCharts',
                'db_table': 'DentalChart_DB',
                'ordering': ('-time_stamp',),
            },
        ),
    ]
