# Generated by Django 4.0 on 2024-04-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_dentalchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalchart',
            name='procedure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='procedure_dental', to='patient.procedure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dentalchart',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_dental', to='patient.patient'),
        ),
    ]
