# Generated by Django 4.0 on 2024-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_dentalchart_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalchart',
            name='time_stamp',
            field=models.DateField(),
        ),
    ]
