# Generated by Django 4.0 on 2024-04-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_alter_userip_failed'),
        ('patient', '0011_alter_dentalchart_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='user_logins',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='procedure_login', to='auth_service.userlogins'),
            preserve_default=False,
        ),
    ]
